//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Activprojetproforma
{
    public partial class _Default : System.Web.UI.Page
    {
        protected void PageLoad(object sender, EventArgs e)
        {

        }
    }
}
