//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activprojetproforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int iddetail { get; set; }
        public string quantitearticle { get; set; }
        public string prix { get; set; }
        public Nullable<int> idcommande { get; set; }
    
        public virtual Commande Commande { get; set; }
    }
}
