//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activprojetproforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligneravitaillement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ligneravitaillement()
        {
            this.LigneravitaillementArticle = new HashSet<LigneravitaillementArticle>();
            this.ligneravitaillement_commande = new HashSet<ligneravitaillement_commande>();
        }
    
        public int idravi { get; set; }
        public string code { get; set; }
        public Nullable<int> idclient { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneravitaillementArticle> LigneravitaillementArticle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligneravitaillement_commande> ligneravitaillement_commande { get; set; }
    }
}
