//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activprojetproforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneravitaillementArticle
    {
        public int idraviacticle { get; set; }
        public string prixunitaire { get; set; }
        public Nullable<int> idarticle { get; set; }
        public string quantite { get; set; }
        public Nullable<int> idravi { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Ligneravitaillement Ligneravitaillement { get; set; }
    }
}
