//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activprojetproforma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<Ligneravitaillement> Ligneravitaillement { get; set; }
        public virtual DbSet<ligneravitaillement_commande> ligneravitaillement_commande { get; set; }
        public virtual DbSet<LigneravitaillementArticle> LigneravitaillementArticle { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
