// <auto-generated />
using System;
using ActivProformaAPI.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActivProformaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220101849_deletedPropertiePrenom")]
    partial class deletedPropertiePrenom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivProformaAPI.Models.Article", b =>
                {
                    b.Property<int>("IdArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArticle"));

                    b.Property<string>("NomArticle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdArticle");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Societe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCommande"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCommande");

                    b.HasIndex("IdClient");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Detail", b =>
                {
                    b.Property<int>("IdDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetail"));

                    b.Property<int>("IdCommande")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantiteArticle")
                        .HasColumnType("int");

                    b.HasKey("IdDetail");

                    b.HasIndex("IdCommande");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Ligneravitaillement", b =>
                {
                    b.Property<int>("IdRavi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRavi"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.HasKey("IdRavi");

                    b.HasIndex("IdClient");

                    b.ToTable("Ligneravitaillements");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.LigneravitaillementArticle", b =>
                {
                    b.Property<int>("IdRaviArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRaviArticle"));

                    b.Property<int>("IdArticle")
                        .HasColumnType("int");

                    b.Property<int>("IdRavi")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("IdRaviArticle");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdRavi");

                    b.ToTable("LigneravitaillementArticles");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.LigneravitaillementCommande", b =>
                {
                    b.Property<int>("IdDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetail"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCommande")
                        .HasColumnType("int");

                    b.Property<int>("IdRavi")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDetail");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdRavi");

                    b.ToTable("LigneravitaillementCommandes");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Commande", b =>
                {
                    b.HasOne("ActivProformaAPI.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Detail", b =>
                {
                    b.HasOne("ActivProformaAPI.Models.Commande", "Commande")
                        .WithMany("Details")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Ligneravitaillement", b =>
                {
                    b.HasOne("ActivProformaAPI.Models.Client", "Client")
                        .WithMany("Ligneravitaillements")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.LigneravitaillementArticle", b =>
                {
                    b.HasOne("ActivProformaAPI.Models.Article", "Article")
                        .WithMany("LigneravitaillementArticles")
                        .HasForeignKey("IdArticle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActivProformaAPI.Models.Ligneravitaillement", "Ligneravitaillement")
                        .WithMany("LigneravitaillementArticles")
                        .HasForeignKey("IdRavi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Ligneravitaillement");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.LigneravitaillementCommande", b =>
                {
                    b.HasOne("ActivProformaAPI.Models.Commande", "Commande")
                        .WithMany("LigneravitaillementCommandes")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ActivProformaAPI.Models.Ligneravitaillement", "Ligneravitaillement")
                        .WithMany("LigneravitaillementCommandes")
                        .HasForeignKey("IdRavi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Ligneravitaillement");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Article", b =>
                {
                    b.Navigation("LigneravitaillementArticles");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Client", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Ligneravitaillements");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Commande", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("LigneravitaillementCommandes");
                });

            modelBuilder.Entity("ActivProformaAPI.Models.Ligneravitaillement", b =>
                {
                    b.Navigation("LigneravitaillementArticles");

                    b.Navigation("LigneravitaillementCommandes");
                });
#pragma warning restore 612, 618
        }
    }
}
